#!/usr/bin/env bash
# gen-manifest.sh — generate MANIFEST.md (top-level) and dumps/MANIFEST.md.
#
# Usage: gen-manifest.sh <KIT_DIR> <KIT_VERSION> <SOURCE_DATE_EPOCH>
#
# Walks every file under <KIT_DIR> (excluding the manifests themselves, build
# artifacts, and scripts/), records filename + size + MD5 + role + provenance,
# and writes two markdown tables. Run from `make manifests` during assembly.
#
# This script is intentionally exhaustive — every file shipped in the tarball
# appears in MANIFEST.md, which selftest.sh re-MD5s against the running kit
# to detect tampering or corrupt downloads.

set -euo pipefail

KIT_DIR="${1:?kit dir required}"
KIT_VERSION="${2:?kit version required}"
SOURCE_DATE_EPOCH="${3:?source date epoch required}"

BUILD_DATE_ISO="$(date -u -d "@${SOURCE_DATE_EPOCH}" +%Y-%m-%d)"

TOP_MANIFEST="${KIT_DIR}/MANIFEST.md"
DUMPS_MANIFEST="${KIT_DIR}/dumps/MANIFEST.md"

# Per-file role+provenance lookup. Keep in sync with the source tree layout
# documented in README.md. Files not in this table get role=auxiliary.
role_for() {
    case "$1" in
        README.md)                                    echo "doc|kit overview + facilitator stand-up instructions" ;;
        Makefile)                                     echo "build|reproducible build entry point" ;;
        install.sh)                                   echo "installer|one-command Kali stand-up entry point" ;;
        selftest.sh)                                  echo "validator|hardware-free kit-integrity check" ;;
        MANIFEST.md)                                  echo "manifest|this file — top-level kit manifest" ;;
        bin/minipro)                                  echo "binary|minipro 0.7.4 (DavidGriffith fd6b56af) — Linux-AMD64 ELF" ;;
        etc/udev/rules.d/60-minipro.rules)            echo "udev|minipro USB-device tagging rule (TL866A/CS, TL866II+, T48, T56, T76)" ;;
        etc/udev/rules.d/61-minipro-plugdev.rules)    echo "udev|grants MODE=660 + GROUP=plugdev on tagged minipro devices" ;;
        etc/udev/rules.d/61-minipro-uaccess.rules)    echo "udev|tags minipro devices with TAG+=uaccess (logind seat access)" ;;
        docs/FACILITATOR-GUIDE.md)                    echo "doc|facilitator-facing workshop runbook (47KB)" ;;
        docs/PARTICIPANT-HANDOUT.md)                  echo "doc|attendee-facing 1-page workshop handout" ;;
        docs/DATAFLASH-DECODE-REFERENCE.md)           echo "doc|AT45DB041E dump format reference (page-0 layout, BCD-B encoding)" ;;
        tools/build-injected.py)                      echo "tool|builds injected.bin from baseline + canonical 3-slot patch" ;;
        tools/recover-baseline.py)                    echo "tool|defensive wrapper around minipro -w; recovers a botched write" ;;
        tools/decode-codes.py)                        echo "tool|reads + decodes the page-0 user-code table (the READ action; renders empty slots)" ;;
        tools/lock-tool.py)                           echo "tool|unified read/write CLI; bakes a custom code into a copy + re-decodes (W2/W3 bedrock)" ;;
        tools/lock-menu.py)                           echo "tool|plain-text menu front-end wrapping lock-tool.py (thin convenience layer)" ;;
        tools/lock-panel.py)                          echo "tool|localhost browser control panel: READ button + custom-value field + WRITE button" ;;
        dumps/intact-lock-AT45DB041E-main-2026-05-20.bin) echo "dump|canonical intact-lock baseline (540,672 bytes, sensitive, workshop-internal)" ;;
        dumps/workshop-sample-3codes-AT45DB041E-2026-05-20.bin) echo "dump|teaching sample (540,672 bytes, sensitive, workshop-internal): canonical baseline + the 3 default workshop codes injected additively at slots 19/32/49; default READ source for the tools" ;;
        dumps/MANIFEST.md)                            echo "manifest|sub-manifest for dumps/ — separated because .bin files are sensitive" ;;
        *)                                            echo "auxiliary|unclassified kit file" ;;
    esac
}

cd "${KIT_DIR}"

# Collect all kit files (excluding the manifests themselves and scripts/, which
# is a build-time-only helper directory — selftest does not need to verify it
# because it is not shipped in the tarball anyway; see Makefile --exclude.)
mapfile -t FILES < <(
    find . -type f \
        ! -path './MANIFEST.md' \
        ! -path './dumps/MANIFEST.md' \
        ! -path './scripts/*' \
        ! -path './.git/*' \
        ! -path '*/__pycache__/*' \
        ! -name '*.pyc' \
        | sed 's|^\./||' | LC_ALL=C sort
)

# Top-level manifest
{
    echo "# facilitator-kit-toorcamp-2026 — MANIFEST"
    echo
    echo "- **Kit version:** ${KIT_VERSION}"
    echo "- **Build date (UTC):** ${BUILD_DATE_ISO}"
    echo "- **Reproducible:** yes (SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}, sorted file order, gzip --no-name)"
    echo "- **Generated by:** scripts/gen-manifest.sh (do not hand-edit)"
    echo
    echo "## File table"
    echo
    echo "Every file shipped in \`facilitator-kit-toorcamp-2026.tar.gz\`. \`selftest.sh\` re-MD5s each entry against the running kit to detect corruption or tampering."
    echo
    echo "| Path | Size (bytes) | MD5 | Role | Provenance |"
    echo "|---|---:|---|---|---|"
    for f in "${FILES[@]}"; do
        size=$(stat -c %s "$f")
        md5=$(md5sum "$f" | awk '{print $1}')
        role_prov=$(role_for "$f")
        role="${role_prov%%|*}"
        prov="${role_prov#*|}"
        # Escape any pipe chars in the provenance for markdown safety
        prov_escaped="${prov//|/\\|}"
        printf "| \`%s\` | %s | \`%s\` | %s | %s |\n" "$f" "$size" "$md5" "$role" "$prov_escaped"
    done
    echo
    echo "## Sensitive content"
    echo
    echo "The two \`dumps/*.bin\` files derive from a captured memory image of a real Alarm Lock T2/T3 unit: \`intact-lock-AT45DB041E-main-2026-05-20.bin\` (the code-free canonical recovery baseline) and \`workshop-sample-3codes-AT45DB041E-2026-05-20.bin\` (the teaching sample — the baseline with the three default workshop codes injected additively, and the tools' default READ source). Treat both as workshop-internal: do not redistribute outside facilitator chain-of-custody. See \`dumps/MANIFEST.md\` for the dump-specific sub-manifest and provenance chain."
} > "${TOP_MANIFEST}"

# Dumps sub-manifest
{
    echo "# dumps/ — sub-manifest"
    echo
    echo "Sensitive content. The \`.bin\` files here derive from a captured memory image of a real Alarm Lock T2/T3 lock board. Two ship: the code-free canonical recovery baseline, and a teaching sample (the baseline with the three default workshop codes injected additively). See \`../docs/DATAFLASH-DECODE-REFERENCE.md\` for the dump format + validation reference."
    echo
    echo "| File | Size (bytes) | MD5 | Provenance |"
    echo "|---|---:|---|---|"
    cd "${KIT_DIR}/dumps"
    for f in $(find . -type f -name '*.bin' | sed 's|^\./||' | LC_ALL=C sort); do
        size=$(stat -c %s "$f")
        md5=$(md5sum "$f" | awk '{print $1}')
        case "$f" in
            intact-lock-AT45DB041E-main-2026-05-20.bin)
                prov="canonical intact-lock baseline; two independent bench reads byte-identical to this MD5; used as recover-baseline.py default; code-free so the MD5 recovery gate is never corrupted; AT45DB041E main array (2048 pages * 264 bytes)"
                ;;
            workshop-sample-3codes-AT45DB041E-2026-05-20.bin)
                prov="teaching sample: canonical baseline + the 3 default workshop codes injected additively at slots 19/32/49 (133769 Master / 420420 Elevated / 696969 Supervisor); default READ source for decode-codes.py and lock-tool.py; AT45DB041E main array (2048 pages * 264 bytes)"
                ;;
            *)
                prov="unclassified dump"
                ;;
        esac
        printf "| \`%s\` | %s | \`%s\` | %s |\n" "$f" "$size" "$md5" "$prov"
    done
} > "${DUMPS_MANIFEST}"

echo "    [manifest] $(wc -l < "${TOP_MANIFEST}") lines top-level, $(wc -l < "${DUMPS_MANIFEST}") lines dumps/"
